# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a19d93ff12180540468c8af05e4da5fca6c0ebc333dd4aa4d2c2ecbeab734a0664ad88a838b5d9bb0f17638e3b0d153bd898cf3ed57941159aa178e92806b0e
  solr_url: http://localhost:8983/solr/development
test:
  secret_key_base: c7646c5c8507dbeee4c86141696e46c49329253717f7cc38d9ffaf9cea52206952619d2e5ad1c7b37f699ff247f97a1840eccaa8c5404c714bf5f39d85f44557
  solr_url: http://localhost:8983/solr/test
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  solr_url: http://localhost:8983/solr/production